# Site settings
title: "Weijia Zhang"
description: "Software Engineer at Google. Information retrieval and natural language generation."
url: "https://wjzhang392.github.io"
baseurl: "" # This site is served at the domain root, so no subpath.
repository: "wjzhang392/wjzhang392.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

exclude:
  - Gemfile
  - Gemfile.lock
  - README-template.md
  - vendor/

# timezone: America/Los_Angeles

collections:
  - publications
  - news
